services:
  - type: web
    name: web_project_final
    env: python
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
